"""
HTML/Markdown report export — pure stdlib, no Jinja or extra deps.
Generates a self-contained HTML file with inline CSS for a polished,
brandable look.
"""
import html
from datetime import datetime, timezone
from typing import Any


def _now():
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


def export_markdown(target: str, target_type: str, evidence_list: list,
                    threat_score: dict | None = None,
                    ai_report: str | None = None,
                    entities: list | None = None,
                    attack_findings: list | None = None) -> str:
    lines = [
        f"# OSINT Investigation Report",
        f"",
        f"**Target:** `{target}`  ",
        f"**Type:** `{target_type}`  ",
        f"**Generated:** {_now()}  ",
        f"**Platform:** Argus OSINT",
        f"",
        "---",
        "",
    ]

    # Threat score
    if threat_score:
        lines.append("## Threat Assessment")
        lines.append("")
        lines.append(f"- **Score:** {threat_score.get('score', 0)}/100")
        lines.append(f"- **Level:** {threat_score.get('level', 'UNKNOWN')}")
        lines.append(f"- **Suggested TLP:** {threat_score.get('tlp', 'AMBER')}")
        lines.append(f"- **Kill-chain stages:** {', '.join(threat_score.get('kill_chain_stages', []))}")
        lines.append("")

        if threat_score.get("indicators"):
            lines.append("### Indicators")
            lines.append("")
            for ind in threat_score["indicators"]:
                lines.append(f"- **{ind['category']}** ({ind['severity']}): {ind['detail']}")
            lines.append("")

        if threat_score.get("recommendations"):
            lines.append("### Recommendations")
            lines.append("")
            for rec in threat_score["recommendations"]:
                lines.append(f"- {rec}")
            lines.append("")
        lines.append("---")
        lines.append("")

    # MITRE ATT&CK findings
    if attack_findings:
        lines.append("## MITRE ATT&CK Mapping")
        lines.append("")
        lines.append("| Technique | Tactic | Evidence |")
        lines.append("|---|---|---|")
        for f in attack_findings:
            lines.append(f"| {f['technique_id']} — {f['name']} | {f['tactic']} | {f.get('evidence','')[:80]} |")
        lines.append("")
        lines.append("---")
        lines.append("")

    # AI report
    if ai_report:
        lines.append("## AI Intelligence Report")
        lines.append("")
        lines.append(ai_report)
        lines.append("")
        lines.append("---")
        lines.append("")

    # Extracted entities
    if entities:
        lines.append("## Extracted Entities (IOCs)")
        lines.append("")
        lines.append("| Type | Value | Source |")
        lines.append("|---|---|---|")
        for e in entities:
            lines.append(f"| {e['type']} | `{e['value']}` | {e.get('source','')} |")
        lines.append("")
        lines.append("---")
        lines.append("")

    # Evidence breakdown
    lines.append("## Evidence Breakdown")
    lines.append("")
    for ev in evidence_list:
        plugin_name = ev.get("plugin_name") if isinstance(ev, dict) else getattr(ev, "plugin_name", "")
        data = ev.get("data") if isinstance(ev, dict) else getattr(ev, "data", {})
        success = ev.get("success", True) if isinstance(ev, dict) else getattr(ev, "success", True)
        if not plugin_name:
            continue
        icon = "✅" if success else "❌"
        lines.append(f"### {icon} {plugin_name}")
        lines.append("")
        if isinstance(data, dict):
            for k, v in data.items():
                v_str = str(v)
                if len(v_str) > 200:
                    v_str = v_str[:200] + "..."
                lines.append(f"- **{k}:** `{v_str}`")
        else:
            lines.append(f"```{str(data)[:1000]}```")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("*Generated by [Argus OSINT Platform](https://github.com/marwannaili237/Argus)*")
    return "\n".join(lines)


def export_html(target: str, target_type: str, evidence_list: list,
                threat_score: dict | None = None,
                ai_report: str | None = None,
                entities: list | None = None,
                attack_findings: list | None = None) -> str:
    """Self-contained HTML report with inline CSS (Argus dark theme)."""
    md = export_markdown(target, target_type, evidence_list, threat_score, ai_report, entities, attack_findings)
    # Minimal Markdown → HTML (good enough for reports)
    import re
    html_body = html.escape(md)
    # Convert Markdown patterns to HTML
    html_body = re.sub(r"^### (.+)$", r"<h3>\1</h3>", html_body, flags=re.MULTILINE)
    html_body = re.sub(r"^## (.+)$", r"<h2>\1</h2>", html_body, flags=re.MULTILINE)
    html_body = re.sub(r"^# (.+)$", r"<h1>\1</h1>", html_body, flags=re.MULTILINE)
    html_body = re.sub(r"^\*\*(.+?)\*\*", r"<strong>\1</strong>", html_body)
    html_body = re.sub(r"`([^`]+)`", r"<code>\1</code>", html_body)
    html_body = re.sub(r"^\- (.+)$", r"<li>\1</li>", html_body, flags=re.MULTILINE)
    html_body = re.sub(r"^---$", r"<hr>", html_body, flags=re.MULTILINE)
    html_body = re.sub(r"(<li>.*?</li>\n?)+", lambda m: f"<ul>{m.group(0)}</ul>", html_body, flags=re.DOTALL)
    html_body = html.escape(html_body)  # we'll re-unesce entities we just added
    html_body = html_body.replace("&lt;h1&gt;", "<h1>").replace("&lt;/h1&gt;", "</h1>")
    html_body = html_body.replace("&lt;h2&gt;", "<h2>").replace("&lt;/h2&gt;", "</h2>")
    html_body = html_body.replace("&lt;h3&gt;", "<h3>").replace("&lt;/h3&gt;", "</h3>")
    html_body = html_body.replace("&lt;strong&gt;", "<strong>").replace("&lt;/strong&gt;", "</strong>")
    html_body = html_body.replace("&lt;code&gt;", "<code>").replace("&lt;/code&gt;", "</code>")
    html_body = html_body.replace("&lt;li&gt;", "<li>").replace("&lt;/li&gt;", "</li>")
    html_body = html_body.replace("&lt;ul&gt;", "<ul>").replace("&lt;/ul&gt;", "</ul>")
    html_body = html_body.replace("&lt;hr&gt;", "<hr>")

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Argus Report — {html.escape(target)}</title>
<style>
body{{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#0a0a0f;color:#e0e0e0;max-width:980px;margin:40px auto;padding:24px;line-height:1.6}}
h1{{color:#e94560;border-bottom:2px solid #16213e;padding-bottom:12px}}
h2{{color:#00d26a;margin-top:32px;border-left:4px solid #00d26a;padding-left:12px}}
h3{{color:#6ea8fe;margin-top:24px}}
code{{background:#1a1a2e;padding:2px 6px;border-radius:4px;color:#f5a623;font-family:'SFMono-Regular',Consolas,monospace;font-size:.85rem}}
pre{{background:#1a1a2e;padding:12px;border-radius:8px;overflow-x:auto}}
ul{{padding-left:20px}}li{{margin:4px 0}}
hr{{border:none;border-top:1px solid #16213e;margin:32px 0}}
table{{border-collapse:collapse;width:100%;font-size:.85rem;margin:16px 0}}
th,td{{border:1px solid #16213e;padding:8px 12px;text-align:left}}
th{{background:#1a1a2e;color:#888;text-transform:uppercase;font-size:.78rem;letter-spacing:.5px}}
tr:hover td{{background:rgba(15,52,96,.3)}}
.footer{{margin-top:48px;padding-top:16px;border-top:1px solid #16213e;color:#888;font-size:.85rem;text-align:center}}
</style>
</head>
<body>
{html_body}
<div class="footer">Generated by Argus OSINT Platform · {_now()}</div>
</body>
</html>"""
